name: OldRaids
version: '${project.version}'
main: me.twostinkysocks.oldraids.OldRaids
api-version: 1.21
commands:
  oldraids:
    usage: /<command>
permissions:
  oldraids.reload:
    description: Reload the plugin
    default: false